---
title: "I'm Opting Out"
description: |
  And I'm relieved
author:
  - name: Michael Mullarkey, PhD (Click to return to my website)
    url: https://mcmullarkey.github.io
date: 05-18-2021
draft: true
output:
  distill::distill_article:
    self_contained: false
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## I'll Never Be a Professor, and I'm Relieved

When I was 4 I wanted to be a cowboy,^[or Robin Hood] when I was 24 I wanted to be a professor, and now I don't know what I want to be. <br>
<br>
I'm opting out of the professor track. I'm not going to hustle 1st author papers, feverishly write grants as a PI, or apply to any professor jobs. Ever.

## But You've Been So Privileged and Lucky at Each Step!

Yep, and I still want out. I have a privilege stack that goes halfway to the moon^[straight white dude, grew up well off, have great/supportive parents (one of whom has a PhD while the other was the first woman student body president in her university's history), behaviorally supportive advisers at the PhD/postdoc level, the list goes on] and I've already been "struck by lightning" level lucky at least three times.^[getting into a PhD program in clinical psychology after receiving 0 official interviews during my application cycle, matching to the one internship site where I could live in the same physical place as my partner, and getting a dream postdoc where I could also live with my partner] <br>
<br>
I also realize I'd have to be that lucky at least two more times^[Both my partner and I getting tenure-track jobs in the same general location and then both of us getting tenure] if I wanted to stay on the professor track. I've gotten more realistic about the likelihood of that happening,^[preposterously unlikely! seriously y'all] but the main reason I'm opting out is a bit different.

## Professor Is At Least 13 Jobs (I Counted)

Professors in clinical psychology are asked to: <br>
<br>
1. Get grants^[Job = Grant Writer] <br>
2. Oversee/perform data collection^[Job = Head of Survey Firm] <br>
3. Clean/preprocess data^[Job = Data Engineer] <br>
4. Store data in a safe, reliable way^[Job = Data Manager] <br>
5. Analyze the data^[Job = Data Scientist/Statistician] <br>
6. Write reports based on the data/publish them^[Job = Research Scientist/Technical Writer] <br>
7. Publicize research results^[Job = Science Communicator/Public Relations] <br>
8. Review others' research papers^[Job = Copy editor (just kidding, Editor)] <br>
9. Review others' grants^[Job = Grant Reviewer (yes, that's a job)] <br>
<br>
That's already so much! But wait, that's only the research part of the process. You also have to: <br>
<br>
10. Interview/hire graduate students and staff^[Job = Recruiter/Hiring Manager] <br>
11. Mentor students/staff^[Job = Manager] <br>
12. Provide clinical supervision/consultation/see patients^[Job = Licensed Mental Health Provider] <br>
13. Teach classes^[Job = Teacher] <br>
<br>
I also know for sure I'm leaving out other important roles clinical psychology professors play. And I was still able to come up with at least 13 separate jobs without thinking very hard. Check the footnotes next to each "role" for the entire job that "role" represents in other organizations.^[I understand too much atomization of people's jobs also isn't great, and I think it's worth thinking about *how many* of these "roles" we ask professors to play] <br>
<br>
I was more willing to try to run this gauntlet when I believed being a professor was the best way *for me* to do rigorous research that improves mental health. I don't believe that anymore.

## I've Lost Faith Being a Professor is a Reliable, Repeatable Path to Improving Mental Health

Mental health outcomes haven't gotten better in decades. We've told ourselves complicated stories about why our "cutting-edge" research isn't translating to better outcomes for people.^[These often involve publishing even more papers with "Research-Practice" gap somewhere in the title] But there's a much simpler story that's much harder for us to hear. <br>
<br>
Our studies almost never have enough people in them to know how good our treatments actually are,^[much less which treatments work best for which people] our research overwhelmingly exclude folks with minoritized identities,^[from the researchers to the participants] and our efforts to disseminate these shakier-than-we-want-to-admit treatments often end when the grant does. <br>
<br>
Doing clinical intervention research well is *devastatingly hard*^[did you see that list of 13 jobs??] even if all the incentives are aligned toward helping people. Our current scientific culture + incentives set up people to never help a single patient outside of research. You are fighting uphill to do just one of increasing sample size, conducting research among folks with any minoritized identities,^[much less intersecting ones] or setting up infrastructure that makes treatment dissemination sustainable. All three at once? Yikes. <br>
<br>
And even if you can run that study, you still have to clean the data, analyze it, and report what actually happened. If we want to make people's lives better we have to report when all of this doesn't work too.^[which is likely the norm rather than the exception] However, reporting "we tried, but it didn't work" can make getting grants/publications even harder.^[I believe it's easier to publish these kinds of results than it was 10 years ago, especially if you have resources, but it's still a far cry from easy] <br>
<br>
For me, improving mental health through doing research as a lone PI with all these "roles" looks like fitting a camel through the eye of a needle. I care deeply about wider ranging, more equitable access to rigorously tested mental health treatments. I'm opting out *because* I care about more equitable access to effective treatment. I think opting out will make it more likely I can be useful toward making that reality happen, not less.^[a bit more on this later in the post]

## This is My Choice, Not a Condemnation

There *are* people in this space who somehow manage to do all of these jobs while working toward increasing equity, rigor, and beneficial outcomes for patients. I've been lucky enough to work for two of them. I also don't think it's a coincidence that both of them were flush with grant money. They could afford to reduce the number of roles they had to play, and even then they are still doing *so much*.^[yes, both of them are amazing humans with incredible skills... and they could also hire lots of staff + buy themselves out of some other obligations] <br>
<br>
I'm not saying no one should be a professor. I'm not pretending I have all^[or any of] the answers, and I totally understand if people disagree with my assessment of the field.^[and they could disagree about whether the field incentivizes helping people, whether the field should be concerned with directly helping people, etc.] Or they agree with my assessment and decide they can best improve patient outcomes by staying on the PI track.^[my values and skills are not the same as others' values/skills, and it's going to take at least several villages working together to get us where we need to go] <br>
<br>
I would be thrilled to be wrong about the state of the field in as many ways as possible. Even if I'm right, I hope there are PIs inside this shot to hell system who keep fighting to make academic clinical psychology a more equitable, rigorous, and beneficial-to-patients space. <br>
<br>
And I also realize those folks are adding at least one more full-time job to their pile.

## What's Next?

I know what I want to *do*. Despite academia's^[and capitalism's] best efforts, I've learned to separate what I want to do from a specific job title. I'll still be trying to solve hard data problems, working to increase mental health treatment access/effectiveness, and talking shit on [Twitter](https://twitter.com/mcmullarkey){target="_blank"} about how our science isn't good enough^[it just isn't y'all, and it's not even close] to actually help people yet. <br>
<br>
In the short-term, I've transitioned into the Director of Data Science role at the Lab for Scalable Mental Health with Dr. Jessica Schleider. I'm super excited to be involved with clinical trials that are large enough to learn what we want to know, accessible to folks with all kinds of intersecting identities, and include treatments that are already being actively disseminated in multiple ways. This way I can primarily focus on doing jobs 2-5 in the list above^[with some dashes of others] rather than all 13.

## We Don't Have to Do 13 Jobs to Be Good Enough

I've made peace with the fact that while I kind of like all 13 of those jobs, there are some I vastly prefer to others and *that doesn't mean I'm not good enough*. I'd much rather spend my time trying to figure out a difficult data science problem than write another cover letter for a paper that's already been rejected four times.^[yep, not a fully fair comparison, but it actually kind of is] <br>
<br>
I'm taking both weekend days off for the first time in an embarrassingly long time. I have time to learn new skills^[Bayesian stats, Python, and others!] that used to consistently fall by the wayside. I'm competing in a [live-streamed data science competition.](https://www.notion.so/Sliced-Show-c7bd26356e3a42279e2dfbafb0480073){target="_blank"}^[that will almost certainly be a humbling, yet awesome experinece!] Come August, I'll get a substantial raise that's still nowhere close to what I might be able to get if I had jumped all the way out of academia. All of those are quality of life improvements that made my decision a lot easier.

## We Don't Have to Stay

I've also made peace with the near certainty of leaving academia entirely at some point. Even at a salary point much lower than industry's, my PI can only guarantee my salary for 1 year. This isn't my PI's fault, and she's fought for me every step of the way. But in order to fund a data scientist position you have to win the grant lottery consistently, and you also have to convince the funder to actually pay the data scientist more than a postdoc. There's no guarantee any of the grants we apply for will happen at all. Even if one of the grants works out there's no guarantee they'll agree to pay me a reasonable salary. Rinse that and repeat every funding cycle, and the math gets really hard.<br> 
<br>
So, there's a decent chance mental health treatment access/effectiveness could become outside projects rather than 9-5s for me. I'm ok with that. In fact, I get really excited when I think about doing a job where I'm solving problems with 100s of thousands of data points rather than a few thousand at best. If you'd like to talk about consulting roles or data scientist roles, feel free to check out my consulting page [here](https://mcmullarkey.github.io/consulting.html){target="_blank"} and my resume [here.](https://mcmullarkey.github.io/resume_markdown.pdf){target="_blank"} You can get in touch with me via e-mail [here.](mailto:mullarkey.mike@gmail.com) <br> 
<br>
I've made the calculation that I'm more likely to improve people's mental health by attempting some of my outside projects and "failing" than becoming a PI and "succeeding." I might be hilariously wrong about that, but I'm excited to see how those projects go.^[none of these are ready for primetime yet, and as soon as they are I'm excited to share them with everyone!]

## What Does This All Mean?

Whatever you want it to, and I really just want what's best for you. If you're on the fence about whether you have to stay in academia or not, I genuinely don't know what you should do. I think there are serious problems with academia, but it's not like industry, private practice, or anywhere else is perfect. What I'm proudest of: making decisions prioritizing what I wanted to do over whether I had the title/trajectory I'd been conditioned to want. <br>
<br>
I feel simultaneously like I've said way too much and not nearly enough. There's a chance I'll talk more about this decision at some point, but I'm going to leave it here for now. I hope you're doing as well as you can be as you read this, and if you're not you deserve better circumstances.




